export const homeObjTwo = {
    id: 'shop',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Made with Bamboo Fibers',
    buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/asset4.png').default,
    img3: require('../../images/asset3.png').default,
    alt: 'model',
    dark: true,
    primary: true,
    darkText: false,
};
