export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Get Pumped',
    headline: 'All New Release',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque facilisis consequat felis eu efficitur. Duis nec vestibulum ante. Etiam tincidunt, quam at ultrices posuere',
    buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/asset5.png').default,
    alt: 'model',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'faq',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Get Pumped',
    headline: 'All New Release',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque facilisis consequat felis eu efficitur. Duis nec vestibulum ante. Etiam tincidunt, quam at ultrices posuere',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/asset2.png').default,
    alt: 'model',
    dark: true,
    primary: true,
    darkText: false,
};